flowchart TD
  prototype[Prototyping]
  requirements[Requirements engineering]
  tara[Threat assessment and remediation analysis]
  implementation[Implementation]
  
  prototype <--> requirements
  prototype .-> tara
  tara <--> requirements
  requirements <--> implementation
