architecture-beta
  group simbank[SIM bank]
  group consumer[Consumer]

  service sim(solar:sim-card-linear)[Smart card]
  service ue(solar:wi-fi-router-linear)[Teltonika RUT200]

  service reader(solar:flash-drive-linear)[Smart card reader] in simbank
  service rpi1(solar:ssd-square-linear)[Raspberry Pi] in simbank

  service simtrace(solar:flash-drive-linear)[SIMtrace 2] in consumer
  service rpi2(solar:ssd-square-linear)[Raspberry Pi] in consumer

  sim:T <--> B:reader
  reader:R <--> L:rpi1
  ue:T <--> B:simtrace
  simtrace:L <--> R:rpi2
  rpi1:R <-[TCP]-> L:rpi2
