architecture-beta
  group bank[SIM bank]
  group sink[UE sink]

  service sim(solar:sim-card-linear)[Smart card]
  service ue(solar:wi-fi-router-linear)[Teltonika RUT200]

  service reader(solar:flash-drive-linear)[Smart card reader] in bank
  service rpi1(solar:ssd-square-linear)[Raspberry Pi] in bank

  service simtrace(solar:flash-drive-linear)[SIMtrace 2] in sink
  service rpi2(solar:ssd-square-linear)[Raspberry Pi] in sink

  sim:T <--> B:reader
  reader:R <--> L:rpi1
  ue:T <--> B:simtrace
  simtrace:L <--> R:rpi2
  rpi1:R <-[TCP]-> L:rpi2
