architecture-beta
  group bank[SIM bank]
  group sink[UE sink]
  group mediator[Mediator]

  service sim(solar:sim-card-linear)[Smart card]
  service ue(solar:wi-fi-router-linear)[User Equipment]

  service reader(solar:flash-drive-linear)[Smart card reader] in bank
  service rpi1(solar:ssd-square-linear)[Bank] in bank

  service simtrace(solar:flash-drive-linear)[SIMtrace 2] in sink
  service rpi2(solar:ssd-square-linear)[Sink] in sink

  service server(solar:server-linear)[Server] in mediator
  service datastore(solar:database-linear)[Data Store] in mediator

  sim:T <--> B:reader
  reader:R <--> L:rpi1
  ue:T <--> B:simtrace
  simtrace:L <--> R:rpi2
  rpi1:R <--> L:server
  rpi2:L <--> R:server
  server:B <--> T:datastore
