architecture-beta
  group simbank[SIM bank]
  group consumer[Consumer]
  group mediator[Mediator]

  service sim(solar:sim-card-linear)[Smart card]
  service ue(solar:wi-fi-router-linear)[User Equipment]

  service reader(solar:flash-drive-linear)[Smart card reader] in simbank
  service rpi1(solar:ssd-square-linear)[Raspberry Pi] in simbank

  service simtrace(solar:flash-drive-linear)[SIMtrace 2] in consumer
  service rpi2(solar:ssd-square-linear)[Raspberry Pi] in consumer

  service server(solar:server-linear)[Server] in mediator
  service datastore(solar:database-linear)[Data Store] in mediator

  sim:T <-[APDU]-> B:reader
  reader:R <-[USB]-> L:rpi1
  ue:T <-[APDU]-> B:simtrace
  simtrace:L <-[USB]-> R:rpi2
  rpi1:R <-[WebSocket]-> L:server
  rpi2:L <-[WebSocket]-> R:server
  server:B <-[SQL]-> T:datastore
