name: Generate PDF
run-name: Generate PDF
on: [push]
jobs:
  generate-latex-pdf:
    runs-on: ubuntu-latest
    steps:
      - run: sudo apt update
      - run: sudo apt install inkscape texlive-latex-base texlive-latex-extra texlive-fonts-recommended texlive-fonts-extra texlive-bibtex-extra biber texlive-lang-european
      - name: Check out repository code
        uses: actions/checkout@v4
      - run: cd ${{ github.workspace }}/docs/whitepaper && ./entrypoint.sh
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4.3.1
        with:
          path: ${{ github.workspace }}/docs/whitepaper/*.pdf
  generate-typst-pdf:
    runs-on: ubuntu-latest
    steps:
      - run: sudo apt update
      - run: sudo apt install nodejs npm
      - name: Check out repository code
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Setup Typst
        uses: typst-community/setup-typst@v4
      - run: cd ${{ github.workspace }}/docs/paper/mermaid-cli && npm install
      - run: cd ${{ github.workspace }}/docs/paper && ./entrypoint.sh
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4.3.1
        with:
          path: ${{ github.workspace }}/docs/paper/*.pdf
